---
- name: Pobierz plik z Linuxa i zapisz na serwerze linux_server
  hosts: ubuntu-22_Host
  tasks:
    - name: Odczytaj zawartość pliku na Linuxie 
      command: cat /home/ubuntu-22/patch/TEST.txt
      register: file_content

    - name: Wyświetl zawartość pliku 
      debug:
        msg: "{{ file_content.stdout }}"

    - name: Wylistuj pliki w katalogu /path na Linuxie
      command: ls /home/ubuntu-22/patch
      register: files_ls 

    - name: Wyświetl listę plików
      debug:
        msg: "{{ files_ls.stdout }}"

    - name: Pobierz plik z Linuxa
      fetch:
        src: /home/ubuntu-22/patch/TEST.txt
        dest: /tmp/ansible_files/TEST.txt
        flat: yes

- name: Skopiuj plik na Linuxa
  hosts: linux-01_Host
  vars:
    nazwa: "pliktestowy"
  tasks:
    - name: Skopiuj plik na Linuxa
      copy:
        src: /tmp/ansible_files/TEST.txt
        dest: /home/TEST.txt
